[package]
name = "otashoko_server"
version = "0.1.0"
authors = ["OrcaXS Suen <sun16281394@gmail.com>"]

[dependencies]
env_logger = "0.5.12"

juniper = "0.9.2"
tar = "0.4.16"
unrar = "0.4.3"
zip = "0.4.2"
dotenv = "0.13.0"
serde = "1.0.72"
serde_json = "1.0.26"
serde_derive = "1.0.72"
chrono = { version = "0.4.5", features = ["serde"] }

actix = "0.7.3"
actix-web = "0.7.3"

futures = "0.1.23"
uuid = { version = "0.6.5", features = ["serde", "v5"] }

r2d2 = "0.8.2"
r2d2_sqlite = "0.5.0"
rusqlite = "0.14.0"
