[package]
name = "otashoko_server"
version = "0.1.0"
authors = ["OrcaXS Suen <sun16281394@gmail.com>"]

[dependencies]
juniper = "0.9.2"
rocket = "0.3.14"
rocket_codegen = "0.3.14"
rocket_cors = "0.2.3"
tar = "0.4.16"
unrar = "0.4.3"
zip = "0.4.2"
diesel = { version = "1.3.2", features = ["sqlite", "chrono"] }
dotenv = "0.13.0"
serde = "1.0.69"
serde_json = "1.0.22"
serde_derive = "1.0.69"
chrono = { version = "0.4", features = ["serde"] }

[dependencies.rocket_contrib]
version = "0.3.14"
default-features = false
features = ["json"]
