[package]
name = "otashoko"
version = "0.1.0"
authors = ["OrcaXS Suen <sun16281394@gmail.com>"]

[dependencies]
juniper = "0.9.0"
rocket = "0.3.8"
rocket_codegen = "0.3.8"
tar = "0.4"
unrar = "0.4.3"
zip = "0.3"
